# Server
server.port=0

# Database
spring.datasource.url=jdbc:postgresql://localhost:5434/task_scheduler
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.jakarta.persistence.query.timeout=5000

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JobRunr
org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=false
org.jobrunr.dashboard.port=8002

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
